language: node_js
node_js:
- '0.11'
- '0.10'

addons:
  sauce_connect: true
before_install:
- npm install npm -g
- npm install -g zuul
before_script:
- npm install
script: npm run test

env:
  global:
  - secure: iHVZldrPx9zsyaBrOqpuBXY9vxRHoqQF27hPsX0hemTirG47sTDuoUWcjS9Jm98WIJkFRit3Tlcf63Agcb3cPksQ9PsaXuCZ299IqUKwhvuT4sw72a4OY4yNqcQ9bU5oVJu83ocebdgvtUtNm4GC6+8V9tB8bCIX62WvEF13rzvvE0HpItsPXjTUH69qDbHGWsXpklWL9IwyNB2hSkGSqZQxis0fw7FVFBhgFVN4CdrxGc66zWmmf3k+7ia9cCZ0FGpqpDLmEcqJQ+u7okOkjcDUJPAY/cwMshRSB+jwDgevXmbRWUWoW6uWpFAdiH8qBhXy3aarUFeTHcMjYnXsYiYEnbwKeVeJegRFLvQ/DWlZStOZl3qyC1ryGWhU7ffesKwOcrGEb+KfeTFnJszNMaaUjbVEz+/anktGMxLpKabmA4+2te4owsXkr5mb9b46lInVcKTG64z3r8xrN2ahfrafgPdmYBG/GKuTDVAPYkNlo3Y5/Ho07X8/9SmDLDcwAz5+2UULVg6Cl84yEa/xXj0ygZuetwkd3tnsc2qb2/0SDLOTTyhGEQg0fstYg5NxjAOVE631rB+yExdHtpLBT+E/17awVYL/PXcQ6bEYFJg6nj3CIS44JZvGLHcn1JQXTsJ7fRcp2HAgCwuGponLuoJJzc83wWZE0fP7zmJ/qNo=
  - secure: G/tnxBwOx+s781x4b/hnXSZLDzlkgcz8yL3PUHdxEGCe1x9wlZDkTQEwvZUqogIu9qL5WXo5O6PFcSwrybFKN87xPs0mvtq+GblSj4JbmYfUwh3hEQ4sFILZx5oZM9Wh375HGV+H+58GrdgC4lXHv6+3Mislg6HMKNlEEb3EG3zOdGR3TMt6fXE0qKpJxPOIQLsu9TsLaKC64us2tY0Q0OxHlxwNzpauvLGRczUVehZCfvtIN/qnBXLo+IBDq8XfTSKtJgTW3NGPrhCiA+66EiysAX1NTXTOtJCj3qTkuEtGY2ppDNj92guIls3D6CE4mh7+dAeFE6BpI2sksX9eYF1whRpc6l8z/ptMqo/2Qo8D4THxB7iv685lt0735Aonb3qRnfT7fM1vroI6sJ2lAdV5aokDVF49ylul8v8n4NOQ2qhDlcDX8cipSHfw9iF79e2djtA9504mBkKfKWUcxUNneJsi5ALVdmk5SPJzQQ0HfttogrdclrPgpq262DHynTj/EtLBO3IxYfoRdjBGDzwJBL0g2S7NX4Yhrk6YlM1Wd3rAM42j7qEt6ISefveY38EfkM0tb2naBQAt2FDimi8Aej/nugcapWHNg+rqzzOSWkuiHcskblAGHcUwWRNOgykRnaXkGqo0g0b3WEqLb9UCGZeahtWp/m2CT0esl4s=
