language: node_js
node_js:
- '0.12'
addons:
  sauce_connect: true
before_install:
- npm install npm -g
# - npm install -g run-browser
# - npm install -g phantomjs --phantomjs_cdnurl=http://cnpmjs.org/downloads
- npm install -g zuul
before_script:
- npm install
# - npm install istanbul coveralls
script: npm run-script test

env:
  global:
    - secure: XcAm/y357GblRZYkB5g1Naq59DrODlaeaj0uiV+nDdwNUCpf7mlAbOh2FDFrzt1ULBG5/bNPe5DXAySfC1CFbDSDrg2Uf7QMIFyAT2MlGj4D2aG1YCmRM995lKWe/PAMRZ6L62/4btoLRhoYj9bbJ6Jp52o01s/F5BSFt3JYREmYQ+ITVyX0JRiPkj9jr10M+lq4XovLws2W/kHHvG5K7KYTMgQLRbzqXQui+sW5rO802glXDAXrOFsHu9NmRW1abwqGIOLVdTsXsMNrE6hcKlUuG8iJ26E80tpspwIo2R3pJWy9IYT6bi+APR3Hqv+nL2BU/Yavp8Au5MWY6UkAJT/76hJWcRKa6FLkQUGJHuUyiq44N6yIK0VI8J+eTuU6yXz7NxVjtsZ4G8jjbqE4Dcb+CxyG+lL6hmZr+aozCA15njifxHRGMje2wKHsyHX3ECJhFDApEwXj7h09Ew8mqh/X4dRS0Yg/IK9xIeR8kP4Y9etledKJ5vp47sl8KCPzRT0gNTj4SpzEeZ6kbJrwlTdPJuEErsrElwg1ETalqhs4gz33sHLY2YncSoEekmYY3fXeg0cujegEzx/FNkwbm6qvqby1EeHjnKsMFTqhOMocFqnOH8Tw1p8z0bN/OZTpxMS2oViJkwDC1FbDeXodpktrBcWmWvWjqG9hO0yyHRk=
    - secure: K9+fLRJ7s6Th+Kjx5bBjDNv9SqIldN/rtukFtchMbO2C40TqGslkLRHy6hBX2jotKmBgF/eud4po5S8WmUFkwUGMDqbgxKXVPcr287HITTWTOuWYtvWMj1FYuVh7G+sxam2ErZXfA8mtdpjOuQibUTdQ3dgys/CtcmZzMLzFK2dH3u+IiVVyQUmvsxUpBLJ8itilHFkpGcO/OWbot8+AWKbMo4UUVg75dEuWdv0/ViBquVPmIyt1gN1SZPfpFJKZbQT7Caf12fMIRx9OM8e/iKdaWESLBxVGtkKQfcXktoxxAi0deh71VfzSQ2pw8vPwDZbDdZ5EEPUn2TspfZi0QufzN64qP0n6A6scSananygDoaGC+nfZrimOUkLsOZdsKmaVK2cuYfCbKzbwa99CUQ++m1nQt63DhyweEKeQm057WUUbzWwCv+qA/9G1PH/EguRUjXLzzrpPaQQGRyeB0u+KqO3rpihTY/qcluPvCEQiy6lfRYOXW9McdqeVFz68fM1WmFwOWAaDLm4ymbFzk/HXoC9lAHgJEsyoTNDPyRiQ6pHFZRzTdJM9pXsp5eYqebwOI1azY2LAoK5DmJPUUdH+DqJSiFlxGxL0iV2NmoXC1b/ntvG+tEKwAVoAYC0cbeAUVb+udzvMXhNifcztZwajDoCDz9tIckhYSfeg1Fk=
