language: node_js
node_js:
- '0.11'
sudo: required

addons:
  sauce_connect: true
before_install:
- npm install npm -g
- npm install -g zuul
before_script:
- npm install
script: npm run test


env:
  global:
    - secure: aZYlZgIEBT6S5EQMBseLNBQx166Y9HLjBfws7unZfQgyC+/9fjkgjGAkxqKSW6SLuxgIuaNemJ8/AvBoFHCvjUjcgNepSe2u9uOzbEPJWlHWn84ARu+z8/YpmJDd9wPECY5fg5cnzOK1LHCtU2k6HD3xPzE8IEyzjZwlrfkGpnsMjbr8jHzK89SjOo0wm0nzksOqwWnCKBzV8wEToZpurplqVU8v0hXDUbk7WiHZPAzpkfxleL2yMZGe45P+s5MfcHUTHh+imQFc94n2gnEIFQHfzYgeuyhPDZybmMNEq0FTZDe9ilcH38aKqaJ83b6USyD0BFMRrRuUJ9zWto7rrfvEzvze83YOExvXd6ZPhyhxeSur0se80bKqZUrBkOFienpsOZ3TWL7y1NFtOyxcqLpXjtddmVz0IGgWrjziWPHhjnqpcuqt6qK30OyD7ztjuN9P6SJXGPp9AiDxXWC4RHwjRHU72J/L9QNVGedjzIE8po871l4hbyhJOtshpQCBM7FHi5ClYZ8/fgStpxCp5jX6WDHnOdSVgToQ180VLZx3ojUcVXUuVk2i11i8EcQcB32DqntoJrtHHGmlMrzVJ3JkdW3F/UBpdBGAfXyZkiLPOsRHusS/NwsC0OuOpVQdtxg8pxG2hplanv8PxStXnSKJxERqctlVMJmDnPLu9pU=
    - secure: b9m2t5Bj3HlH8jHdJ3XjQFbh9n227pJPOmUBlEeYAyICdZtnKU/nNEpi5+q1rGwn2NofrA1z/t7YriU+DmSCLq01PIaiB49+IP/8UpJJJr/JfegmVyl3wmsq82/y8mJhZvWdnNGS/h+v4aFUCcR5/pzU5E6l3XTKMJiAaqG2eciNLc6blmdxZOboQo6xq6zoZkF3+hwy7/+BYa8BVCEfyPCH6no7mPLZIUBYiDs/hNHo5Lfi8yjdXqVKeihsgRjigeivDz1Ml3xEJFP4TvyyUT+yeiXLl6Z93gYzx7bKDFDua14YiD+4qAZTE1T3QU9/0yRdEjrSLQwlCiqB4Gzp1EXnP7afP6MzusrhwQnFYw1UA8sp79oz3vqb5dNBeKU4LQA6fUeAsDKTkBAN6Y8vQhu4gonxPXfMOb5L6hreZIX0hL/+5j7GAuZmg87pbYZ0OeQ3snZBRg1vXJaLkMs3T3m1LOfTCL6WhfkEgcvkHdPlkWpZ5gokV4NFXEoHyjH21GYzuXWV7Rb62OV1aLV+grG3cCGNsOJt84eYCtpSL8ev1CZChgiuJ9W3eIUsCyd4wBklFhiNuiLXDVjMVj050uyYGyfXaE6Tifv3s9rkpNMO0SRGvuVSNwroyA0To43J/q9hwGkaxw2Gqoi8nQsA3cAILYuy67qhZX9E55M+L/I=
