ui: tape
concurrency: 1
browsers:
  - name: iphone
    version: 5.0..latest

  - name: android
    version: 4.0..latest

  - name: chrome
    version: 26..latest

  - name: firefox
    version: 3.0..latest

  - name: safari
    version: 5..latest

  - name: ipad
    version: 4.3..latest

  - name: internet explorer
    version: 9..latest
